#pragma once
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define VIAL_KEYBOARD_UID {0x66, 0xFF, 0x74, 0x6F, 0x5D, 0x57, 0x38, 0x32}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 5 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 15 }

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP
// #define RGB_MATRIX_DEFAULT_HUE 0
// #define RGB_MATRIX_DEFAULT_SAT 255
// #define RGB_MATRIX_DEFAULT_VAL 96
#define RGB_MATRIX_DEFAULT_SPD 7

#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
