#pragma once

// Layer
#define DYNAMIC_KEYMAP_LAYER_COUNT 6
// RGB Layer
#define EFFECT_LAYERS 6
#define EFFECTS_PER_LAYER 2

#define VIAL_KEYBOARD_UID {0x41, 0xB7, 0x88, 0x65, 0xDC, 0x38, 0x0E, 0xE8}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 5 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 15 }

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP
// #define RGB_MATRIX_DEFAULT_HUE 0
// #define RGB_MATRIX_DEFAULT_SAT 255
// #define RGB_MATRIX_DEFAULT_VAL 96
#define RGB_MATRIX_DEFAULT_SPD 7

#define VIAL_TAP_DANCE_ENTRIES 6
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 2
#define DYNAMIC_KEYMAP_MACRO_COUNT 4
